# Generated by Django 5.1.3 on 2024-12-09 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('pp', models.IntegerField()),
                ('accuracy', models.IntegerField()),
                ('category', models.CharField(choices=[('physical', 'Physical'), ('special', 'Special'), ('status', 'Status')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('dexnum', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type1', models.CharField(max_length=50)),
                ('type2', models.CharField(blank=True, max_length=50, null=True)),
                ('ability', models.CharField(max_length=100)),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('health', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('special_attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('special_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('learnset', models.ManyToManyField(related_name='learnable_by', to='project.move')),
                ('moveset', models.ManyToManyField(limit_choices_to=4, related_name='used_by', to='project.move')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('bulky offense', 'Bulky Offense'), ('stall', 'Stall'), ('hyper offense', 'Hyper Offense'), ('hazard stack', 'Hazard Stack')], max_length=20)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('pokemon', models.ManyToManyField(related_name='teams', to='project.pokemon')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='project.trainer')),
            ],
        ),
    ]
