# Generated by Django 5.1.3 on 2024-12-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_move_flavor_text_alter_move_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='ev_attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ev_defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ev_special_attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ev_special_defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ev_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='iv_attack',
            field=models.IntegerField(default=31),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='iv_defense',
            field=models.IntegerField(default=31),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='iv_health',
            field=models.IntegerField(default=31),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='iv_special_attack',
            field=models.IntegerField(default=31),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='iv_special_defense',
            field=models.IntegerField(default=31),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='iv_speed',
            field=models.IntegerField(default=31),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='nature',
            field=models.CharField(choices=[('Adamant', 'Adamant'), ('Bashful', 'Bashful'), ('Bold', 'Bold'), ('Brave', 'Brave'), ('Calm', 'Calm'), ('Careful', 'Careful'), ('Docile', 'Docile'), ('Gentle', 'Gentle'), ('Hardy', 'Hardy'), ('Hasty', 'Hasty'), ('Impish', 'Impish'), ('Jolly', 'Jolly'), ('Lax', 'Lax'), ('Lonely', 'Lonely'), ('Mild', 'Mild'), ('Modest', 'Modest'), ('Naive', 'Naive'), ('Naughty', 'Naughty'), ('Quiet', 'Quiet'), ('Quirky', 'Quirky'), ('Rash', 'Rash'), ('Relaxed', 'Relaxed'), ('Sassy', 'Sassy'), ('Serious', 'Serious'), ('Timid', 'Timid')], default='Hardy', max_length=10),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='sprite',
            field=models.URLField(blank=True, null=True),
        ),
    ]
