# Generated by Django 5.1.3 on 2024-12-09 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_pokemon_iv_attack_alter_pokemon_iv_defense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='pp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='iv_attack',
            field=models.IntegerField(default=31),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='iv_defense',
            field=models.IntegerField(default=31),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='iv_health',
            field=models.IntegerField(default=31),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='iv_special_attack',
            field=models.IntegerField(default=31),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='iv_special_defense',
            field=models.IntegerField(default=31),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='iv_speed',
            field=models.IntegerField(default=31),
        ),
        migrations.CreateModel(
            name='TeamPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('nature', models.CharField(choices=[('Adamant', 'Adamant'), ('Bashful', 'Bashful'), ('Bold', 'Bold'), ('Brave', 'Brave'), ('Calm', 'Calm'), ('Careful', 'Careful'), ('Docile', 'Docile'), ('Gentle', 'Gentle'), ('Hardy', 'Hardy'), ('Hasty', 'Hasty'), ('Impish', 'Impish'), ('Jolly', 'Jolly'), ('Lax', 'Lax'), ('Lonely', 'Lonely'), ('Mild', 'Mild'), ('Modest', 'Modest'), ('Naive', 'Naive'), ('Naughty', 'Naughty'), ('Quiet', 'Quiet'), ('Quirky', 'Quirky'), ('Rash', 'Rash'), ('Relaxed', 'Relaxed'), ('Sassy', 'Sassy'), ('Serious', 'Serious'), ('Timid', 'Timid')], default='Hardy', max_length=10)),
                ('ev_health', models.IntegerField(default=0)),
                ('ev_attack', models.IntegerField(default=0)),
                ('ev_special_attack', models.IntegerField(default=0)),
                ('ev_defense', models.IntegerField(default=0)),
                ('ev_special_defense', models.IntegerField(default=0)),
                ('ev_speed', models.IntegerField(default=0)),
                ('moveset', models.ManyToManyField(related_name='team_pokemon_moveset', to='project.move')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.pokemon')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.team')),
            ],
        ),
    ]
