# Generated by Django 5.1.3 on 2024-12-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_move_pp_alter_pokemon_iv_attack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='type',
        ),
    ]
