# Generated by Django 5.1.3 on 2024-12-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_team_type'),
    ]

    state_operations = [
        migrations.AlterField(
            model_name='team',
            name='pokemon',
            field=models.ManyToManyField(related_name='teams', through='project.TeamPokemon', to='project.pokemon'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
    ]
