# Generated by Django 5.1.3 on 2024-12-10 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_team_pokemon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='creation_date',
        ),
        migrations.AlterField(
            model_name='team',
            name='pokemon',
            field=models.ManyToManyField(through='project.TeamPokemon', to='project.pokemon'),
        ),
        migrations.AlterField(
            model_name='team',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.trainer'),
        ),
    ]
